jobs:
- template: azure-pipelines-template.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14

- template: azure-pipelines-template.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
