deps = {'IPython': {'err': AttributeError("module 'docutils.parsers.rst.states' has no attribute '__file__'"),
             'name': 'IPython'},
 '_bcrypt': {'name': '_bcrypt', 'package': "<module '_bcrypt' (built-in)>"},
 '_brotli': {'name': '_brotli', 'package': "<module '_brotli' (built-in)>"},
 '_cares': {'name': '_cares', 'package': "<module '_cares' (built-in)>"},
 '_common': {'name': '_common',
             'package': "<module '_common' from '/home/jayvdb/projects/osc/d-l-py/python-psutil/psutil-5.6.7/psutil/_common.py'>",
             'path': '/home/jayvdb/projects/osc/d-l-py/python-psutil/psutil-5.6.7/psutil/_common.py'},
 '_constant_time': {'name': '_constant_time',
                    'package': "<module '_constant_time' (built-in)>"},
 '_openssl': {'name': '_openssl', 'package': "<module '_openssl' (built-in)>"},
 '_padding': {'name': '_padding', 'package': "<module '_padding' (built-in)>"},
 '_sodium': {'name': '_sodium', 'package': "<module '_sodium' (built-in)>"},
 'a': {'name': 'a',
       'package': "<module 'a' from '/tmp/pytest-of-jayvdb/pytest-354/test_import_string_provides_tr0/a/__init__.py'>",
       'path': '/tmp/pytest-of-jayvdb/pytest-354/test_import_string_provides_tr0/a/'},
 'aspectlib': {'name': 'aspectlib',
               'package': "<module 'aspectlib' from '/usr/lib/python3.7/site-packages/aspectlib/__init__.py'>",
               'path': '/usr/lib/python3.7/site-packages/aspectlib/',
               'ver': '1.4.2'},
 'async_generator': {'name': 'async_generator',
                     'package': "<module 'async_generator' from '/usr/lib/python3.7/site-packages/async_generator/__init__.py'>",
                     'path': '/usr/lib/python3.7/site-packages/async_generator/',
                     'ver': '1.10'},
 'atomicwrites': {'name': 'atomicwrites',
                  'package': "<module 'atomicwrites' from '/usr/lib/python3.7/site-packages/atomicwrites/__init__.py'>",
                  'path': '/usr/lib/python3.7/site-packages/atomicwrites/',
                  'ver': '1.3.0'},
 'b': {'name': 'b',
       'package': "<module 'b' from '/tmp/pytest-of-jayvdb/pytest-354/test_import_string_provides_tr0/b/__init__.py'>",
       'path': '/tmp/pytest-of-jayvdb/pytest-354/test_import_string_provides_tr0/b/'},
 'babel': {'name': 'babel',
           'package': "<module 'babel' from '/usr/lib/python3.7/site-packages/babel/__init__.py'>",
           'path': '/usr/lib/python3.7/site-packages/babel/',
           'ver': '2.6.0'},
 'backcall': {'name': 'backcall',
              'package': "<module 'backcall' from '/usr/lib/python3.7/site-packages/backcall/__init__.py'>",
              'path': '/usr/lib/python3.7/site-packages/backcall/',
              'ver': '0.1.0'},
 'backports_abc': {'name': 'backports_abc',
                   'package': "<module 'backports_abc' from '/usr/lib/python3.7/site-packages/backports_abc.py'>",
                   'path': '/usr/lib/python3.7/site-packages/backports_abc.py'},
 'base_classes': {'name': 'base_classes',
                  'package': "<module 'base_classes' from '/home/jayvdb/projects/osc/devel:languages:python/python-kitchen/kitchen-1.2.6/kitchen3/tests/base_classes.py'>",
                  'path': '/home/jayvdb/projects/osc/devel:languages:python/python-kitchen/kitchen-1.2.6/kitchen3/tests/base_classes.py'},
 'blinker': {'name': 'blinker',
             'package': "<module 'blinker' from '/usr/lib/python3.7/site-packages/blinker/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/blinker/',
             'ver': '1.4'},
 'blueprintapp': {'name': 'blueprintapp',
                  'package': "<module 'blueprintapp' from '/home/jayvdb/projects/osc/devel:languages:python:flask/python-Flask/Flask-1.1.1/tests/test_apps/blueprintapp/__init__.py'>",
                  'path': '/home/jayvdb/projects/osc/devel:languages:python:flask/python-Flask/Flask-1.1.1/tests/test_apps/blueprintapp/'},
 'canonical': {'name': 'canonical',
               'package': "<module 'canonical' from '/home/jayvdb/projects/python/ruamel/yaml/_test/lib/canonical.py'>",
               'path': '/home/jayvdb/projects/python/ruamel/yaml/_test/lib/canonical.py'},
 'case': {'name': 'case',
          'package': "<module 'case' from '/usr/lib/python3.7/site-packages/case/__init__.py'>",
          'path': '/usr/lib/python3.7/site-packages/case/',
          'ver': '1.5.3'},
 'celery': {'name': 'celery',
            'package': "<module 'celery' from '/usr/lib/python3.7/site-packages/celery/__init__.py'>",
            'path': '/usr/lib/python3.7/site-packages/celery/'},
 'cliapp': {'name': 'cliapp',
            'package': "<module 'cliapp' from '/home/jayvdb/projects/osc/devel:languages:python:flask/python-Flask/Flask-1.1.1/tests/test_apps/cliapp/__init__.py'>",
            'path': '/home/jayvdb/projects/osc/devel:languages:python:flask/python-Flask/Flask-1.1.1/tests/test_apps/cliapp/'},
 'colorclass': {'name': 'colorclass',
                'package': "<module 'colorclass' from '/usr/lib/python3.7/site-packages/colorclass/__init__.py'>",
                'path': '/usr/lib/python3.7/site-packages/colorclass/',
                'ver': '2.2.0'},
 'common': {'name': 'common',
            'package': "<module 'common' from '/home/jayvdb/projects/osc/devel:languages:python:numeric/python-tabulate/tabulate-0.8.6/test/common.py'>",
            'path': '/home/jayvdb/projects/osc/devel:languages:python:numeric/python-tabulate/tabulate-0.8.6/test/common.py'},
 'compat': {'name': 'compat',
            'package': "<module 'compat' from '/home/jayvdb/projects/osc/devel:languages:python/python-wrapt/wrapt-1.11.2/tests/compat.py'>",
            'path': '/home/jayvdb/projects/osc/devel:languages:python/python-wrapt/wrapt-1.11.2/tests/compat.py'},
 'cryptography_vectors': {'name': 'cryptography_vectors',
                          'package': "<module 'cryptography_vectors' from '/usr/lib/python3.7/site-packages/cryptography_vectors/__init__.py'>",
                          'path': '/usr/lib/python3.7/site-packages/cryptography_vectors/',
                          'ver': '2.7'},
 'dateparser': {'err': ImportError("No module named '_strptime'"),
                'name': 'dateparser'},
 'dateparser_data': {'name': 'dateparser_data',
                     'package': "<module 'dateparser_data' from '/usr/lib/python3.7/site-packages/dateparser_data/__init__.py'>",
                     'path': '/usr/lib/python3.7/site-packages/dateparser_data/'},
 'django_webtest': {'name': 'django_webtest',
                    'package': "<module 'django_webtest' from '/usr/lib/python3.7/site-packages/django_webtest/__init__.py'>",
                    'path': '/usr/lib/python3.7/site-packages/django_webtest/'},
 'docrepr': {'name': 'docrepr',
             'package': "<module 'docrepr' from '/usr/lib/python3.7/site-packages/docrepr/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/docrepr/',
             'ver': '0.1.1'},
 'dotenv': {'name': 'dotenv',
            'package': "<module 'dotenv' from '/usr/lib/python3.7/site-packages/dotenv/__init__.py'>",
            'path': '/usr/lib/python3.7/site-packages/dotenv/',
            'ver': '0.10.2'},
 'extras': {'name': 'extras',
            'package': "<module 'extras' from '/usr/lib/python3.7/site-packages/extras/__init__.py'>",
            'path': '/usr/lib/python3.7/site-packages/extras/',
            'ver': '1.0.0.final.0'},
 'fastimport': {'name': 'fastimport',
                'package': "<module 'fastimport' from '/usr/lib/python3.7/site-packages/fastimport/__init__.py'>",
                'path': '/usr/lib/python3.7/site-packages/fastimport/',
                'ver': '0.9.8'},
 'fixtureapps': {'name': 'fixtureapps',
                 'package': "<module 'fixtureapps' from './fixtureapps/__init__.py'>",
                 'path': './fixtureapps/'},
 'fixtures': {'name': 'fixtures',
              'package': "<module 'fixtures' from '/usr/lib/python3.7/site-packages/fixtures/__init__.py'>",
              'path': '/usr/lib/python3.7/site-packages/fixtures/',
              'ver': '3.0.0.final.0'},
 'flaky': {'name': 'flaky',
           'package': "<module 'flaky' from '/usr/lib/python3.7/site-packages/flaky/__init__.py'>",
           'path': '/usr/lib/python3.7/site-packages/flaky/'},
 'flasgger': {'name': 'flasgger',
              'package': "<module 'flasgger' from '/usr/lib/python3.7/site-packages/flasgger/__init__.py'>",
              'path': '/usr/lib/python3.7/site-packages/flasgger/',
              'ver': '0.9.2'},
 'frame': {'name': 'frame',
           'package': "<module 'frame' from '/home/jayvdb/projects/osc/devel:languages:python/python-lz4/lz4-2.2.1/tests/frame/__init__.py'>",
           'path': '/home/jayvdb/projects/osc/devel:languages:python/python-lz4/lz4-2.2.1/tests/frame/'},
 'freezegun': {'name': 'freezegun',
               'package': "<module 'freezegun' from '/usr/lib/python3.7/site-packages/freezegun/__init__.py'>",
               'path': '/usr/lib/python3.7/site-packages/freezegun/',
               'ver': '0.3.11'},
 'google': {'name': 'google', 'package': "<module 'google' (namespace)>"},
 'gunicorn': {'name': 'gunicorn',
              'package': "<module 'gunicorn' from '/usr/lib/python3.7/site-packages/gunicorn/__init__.py'>",
              'path': '/usr/lib/python3.7/site-packages/gunicorn/',
              'ver': '19.9.0'},
 'handlers': {'name': 'handlers',
              'package': "<module 'handlers' from '/home/jayvdb/projects/osc/devel:languages:python/python-pyserial/pyserial-3.4/test/handlers/__init__.py'>",
              'path': '/home/jayvdb/projects/osc/devel:languages:python/python-pyserial/pyserial-3.4/test/handlers/'},
 'html5lib': {'name': 'html5lib',
              'package': "<module 'html5lib' from '/usr/lib/python3.7/site-packages/html5lib/__init__.py'>",
              'path': '/usr/lib/python3.7/site-packages/html5lib/',
              'ver': '1.0.1'},
 'httpbin': {'name': 'httpbin',
             'package': "<module 'httpbin' from '/usr/lib/python3.7/site-packages/httpbin/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/httpbin/',
             'ver': '0.9.2'},
 'humanize': {'name': 'humanize',
              'package': "<module 'humanize' from '/usr/lib/python3.7/site-packages/humanize/__init__.py'>",
              'path': '/usr/lib/python3.7/site-packages/humanize/',
              'ver': '0.4'},
 'hypothesis': {'name': 'hypothesis',
                'package': "<module 'hypothesis' from '/usr/lib/python3.7/site-packages/hypothesis/__init__.py'>",
                'path': '/usr/lib/python3.7/site-packages/hypothesis/',
                'ver': '4.46.1'},
 'import_hooks': {'name': 'import_hooks',
                  'package': "<module 'import_hooks' from '/home/jayvdb/projects/import-hooks/import-hooks/import_hooks.py'>",
                  'path': '/home/jayvdb/projects/import-hooks/import-hooks/import_hooks.py'},
 'ipython_genutils': {'name': 'ipython_genutils',
                      'package': "<module 'ipython_genutils' from '/usr/lib/python3.7/site-packages/ipython_genutils/__init__.py'>",
                      'path': '/usr/lib/python3.7/site-packages/ipython_genutils/',
                      'ver': '0.2.0'},
 'iso8601': {'name': 'iso8601',
             'package': "<module 'iso8601' from '/usr/lib/python3.7/site-packages/iso8601/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/iso8601/'},
 'linecache2': {'name': 'linecache2',
                'package': "<module 'linecache2' from '/usr/lib/python3.7/site-packages/linecache2/__init__.py'>",
                'path': '/usr/lib/python3.7/site-packages/linecache2/'},
 'manuel': {'name': 'manuel',
            'package': "<module 'manuel' from '/usr/lib/python3.7/site-packages/manuel/__init__.py'>",
            'path': '/usr/lib/python3.7/site-packages/manuel/'},
 'marshmallow': {'name': 'marshmallow',
                 'package': "<module 'marshmallow' from '/usr/lib/python3.7/site-packages/marshmallow/__init__.py'>",
                 'path': '/usr/lib/python3.7/site-packages/marshmallow/',
                 'ver': '2.19.2'},
 'memcache': {'name': 'memcache',
              'package': "<module 'memcache' from '/usr/lib/python3.7/site-packages/memcache.py'>",
              'path': '/usr/lib/python3.7/site-packages/memcache.py',
              'ver': '1.58'},
 'mimeparse': {'name': 'mimeparse',
               'package': "<module 'mimeparse' from '/usr/lib/python3.7/site-packages/mimeparse.py'>",
               'path': '/usr/lib/python3.7/site-packages/mimeparse.py',
               'ver': '1.6.0'},
 'mistune': {'name': 'mistune',
             'package': "<module 'mistune' from '/usr/lib/python3.7/site-packages/mistune.py'>",
             'path': '/usr/lib/python3.7/site-packages/mistune.py',
             'ver': '0.8.4'},
 'mock': {'name': 'mock',
          'package': "<module 'mock' from '/usr/lib/python3.7/site-packages/mock/__init__.py'>",
          'path': '/usr/lib/python3.7/site-packages/mock/',
          'ver': '2.0.0'},
 'mod': {'name': 'mod',
         'package': "<module 'mod' from '/tmp/tmp9iju570v/mod.py'>",
         'path': '/tmp/tmp9iju570v/mod.py'},
 'mytest': {'name': 'mytest',
            'package': "<module 'mytest' from '/home/jayvdb/projects/osc/devel:languages:python/python-logutils/logutils-0.3.5/tests/mytest.py'>",
            'path': '/home/jayvdb/projects/osc/devel:languages:python/python-logutils/logutils-0.3.5/tests/mytest.py'},
 'nose': {'name': 'nose',
          'package': "<module 'nose' from '/usr/lib/python3.7/site-packages/nose/__init__.py'>",
          'path': '/usr/lib/python3.7/site-packages/nose/',
          'ver': '1.3.7'},
 'padme': {'name': 'padme',
           'package': "<module 'padme' from '/usr/lib/python3.7/site-packages/padme/__init__.py'>",
           'path': '/usr/lib/python3.7/site-packages/padme/',
           'ver': '1.1.1'},
 'paramiko': {'name': 'paramiko',
              'package': "<module 'paramiko' from '/usr/lib/python3.7/site-packages/paramiko/__init__.py'>",
              'path': '/usr/lib/python3.7/site-packages/paramiko/',
              'ver': '2.4.2'},
 'paste': {'name': 'paste', 'package': "<module 'paste' (namespace)>"},
 'pbr': {'name': 'pbr',
         'package': "<module 'pbr' from '/usr/lib/python3.7/site-packages/pbr/__init__.py'>",
         'path': '/usr/lib/python3.7/site-packages/pbr/',
         'ver': "<module 'pbr.version' from '/usr/lib/python3.7/site-packages/pbr/version.py'>"},
 'pexpect': {'name': 'pexpect',
             'package': "<module 'pexpect' from '/usr/lib/python3.7/site-packages/pexpect/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/pexpect/',
             'ver': '4.7.0'},
 'pickleshare': {'name': 'pickleshare',
                 'package': "<module 'pickleshare' from '/usr/lib/python3.7/site-packages/pickleshare.py'>",
                 'path': '/usr/lib/python3.7/site-packages/pickleshare.py',
                 'ver': '0.7.5'},
 'plugin_base': {'name': 'plugin_base',
                 'package': "<module 'plugin_base' from '/home/jayvdb/projects/osc/devel:languages:python/python-SQLAlchemy/SQLAlchemy-1.3.11/test/../lib/sqlalchemy/testing/plugin/plugin_base.py'>",
                 'path': '/home/jayvdb/projects/osc/devel:languages:python/python-SQLAlchemy/SQLAlchemy-1.3.11/test/../lib/sqlalchemy/testing/plugin/plugin_base.py'},
 'pretend': {'name': 'pretend',
             'package': "<module 'pretend' from '/usr/lib/python3.7/site-packages/pretend.py'>",
             'path': '/usr/lib/python3.7/site-packages/pretend.py'},
 'ptyprocess': {'name': 'ptyprocess',
                'package': "<module 'ptyprocess' from '/usr/lib/python3.7/site-packages/ptyprocess/__init__.py'>",
                'path': '/usr/lib/python3.7/site-packages/ptyprocess/',
                'ver': '0.6.0'},
 'py3_only_features': {'name': 'py3_only_features',
                       'package': "<module 'py3_only_features' from '/home/jayvdb/projects/osc/devel:languages:python/python-flexmock/flexmock-0.10.4/tests/py3_only_features.py'>",
                       'path': '/home/jayvdb/projects/osc/devel:languages:python/python-flexmock/flexmock-0.10.4/tests/py3_only_features.py'},
 'pylama': {'name': 'pylama',
            'package': "<module 'pylama' from '/usr/lib/python3.7/site-packages/pylama/__init__.py'>",
            'path': '/usr/lib/python3.7/site-packages/pylama/',
            'ver': '7.7.1'},
 'pymysql': {'name': 'pymysql',
             'package': "<module 'pymysql' from '/usr/lib/python3.7/site-packages/pymysql/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/pymysql/',
             'ver': '0.9.3'},
 'redis': {'name': 'redis',
           'package': "<module 'redis' from '/usr/lib/python3.7/site-packages/redis/__init__.py'>",
           'path': '/usr/lib/python3.7/site-packages/redis/',
           'ver': '3.2.1'},
 'requests_mock': {'name': 'requests_mock',
                   'package': "<module 'requests_mock' from '/usr/lib/python3.7/site-packages/requests_mock/__init__.py'>",
                   'path': '/usr/lib/python3.7/site-packages/requests_mock/'},
 'rfc3987': {'name': 'rfc3987',
             'package': "<module 'rfc3987' from '/usr/lib/python3.7/site-packages/rfc3987.py'>",
             'path': '/usr/lib/python3.7/site-packages/rfc3987.py',
             'ver': '1.3.8'},
 'roundtrip': {'name': 'roundtrip',
               'package': "<module 'roundtrip' from '/home/jayvdb/projects/python/ruamel/yaml/_test/roundtrip.py'>",
               'path': '/home/jayvdb/projects/python/ruamel/yaml/_test/roundtrip.py'},
 'scikits': {'name': 'scikits',
             'package': "<module 'scikits' from '/usr/lib/python3.7/site-packages/scikits/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/scikits/'},
 'simple_unit_tests': {'name': 'simple_unit_tests',
                       'package': "<module 'simple_unit_tests' from '/home/jayvdb/projects/osc/devel:languages:python/python-pyparsing/pyparsing-2.4.5/simple_unit_tests.py'>",
                       'path': '/home/jayvdb/projects/osc/devel:languages:python/python-pyparsing/pyparsing-2.4.5/simple_unit_tests.py'},
 'some_module': {'name': 'some_module',
                 'package': "<module 'some_module' from '/home/jayvdb/projects/osc/devel:languages:python/python-flexmock/flexmock-0.10.4/tests/some_module.py'>",
                 'path': '/home/jayvdb/projects/osc/devel:languages:python/python-flexmock/flexmock-0.10.4/tests/some_module.py'},
 'sphinx': {'name': 'sphinx',
            'package': "<module 'sphinx' from '/usr/lib/python3.7/site-packages/sphinx/__init__.py'>",
            'path': '/usr/lib/python3.7/site-packages/sphinx/',
            'ver': '1.8.5'},
 'sphinxcontrib': {'name': 'sphinxcontrib',
                   'package': "<module 'sphinxcontrib' (namespace)>"},
 'sqla_plugin_base': {'name': 'sqla_plugin_base',
                      'package': "<module 'plugin_base' from '/home/jayvdb/projects/osc/devel:languages:python/python-SQLAlchemy/SQLAlchemy-1.3.11/test/../lib/sqlalchemy/testing/plugin/plugin_base.py'>",
                      'path': '/home/jayvdb/projects/osc/devel:languages:python/python-SQLAlchemy/SQLAlchemy-1.3.11/test/../lib/sqlalchemy/testing/plugin/plugin_base.py'},
 'sqla_pytestplugin': {'name': 'sqla_pytestplugin',
                       'package': "<module 'pytestplugin' from '/home/jayvdb/projects/osc/devel:languages:python/python-SQLAlchemy/SQLAlchemy-1.3.11/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py'>",
                       'path': '/home/jayvdb/projects/osc/devel:languages:python/python-SQLAlchemy/SQLAlchemy-1.3.11/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py'},
 'strict_rfc3339': {'name': 'strict_rfc3339',
                    'package': "<module 'strict_rfc3339' from '/usr/lib/python3.7/site-packages/strict_rfc3339.py'>",
                    'path': '/usr/lib/python3.7/site-packages/strict_rfc3339.py'},
 'string_asserts': {'name': 'string_asserts',
                    'package': "<module 'string_asserts' from '/home/jayvdb/projects/python/pygments/tests/string_asserts.py'>",
                    'path': '/home/jayvdb/projects/python/pygments/tests/string_asserts.py'},
 'subunit': {'name': 'subunit',
             'package': "<module 'subunit' from '/usr/lib/python3.7/site-packages/subunit/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/subunit/',
             'ver': '1.3.0.final.0'},
 'support': {'name': 'support',
             'package': "<module 'support' from '/home/jayvdb/projects/python/pygments/tests/support.py'>",
             'path': '/home/jayvdb/projects/python/pygments/tests/support.py'},
 't': {'name': 't',
       'package': "<module 't' from '/home/jayvdb/projects/osc/devel:languages:python/python-vine/vine-1.3.0/t/__init__.py'>",
       'path': '/home/jayvdb/projects/osc/devel:languages:python/python-vine/vine-1.3.0/t/'},
 'testing': {'name': 'testing',
             'package': "<module 'testing' from '/home/jayvdb/projects/osc/devel:languages:python/python-cffi/cffi-1.13.2/testing/__init__.py'>",
             'path': '/home/jayvdb/projects/osc/devel:languages:python/python-cffi/cffi-1.13.2/testing/'},
 'testtools': {'name': 'testtools',
               'package': "<module 'testtools' from '/usr/lib/python3.7/site-packages/testtools/__init__.py'>",
               'path': '/usr/lib/python3.7/site-packages/testtools/',
               'ver': '2.3.0.final.0'},
 'traceback2': {'name': 'traceback2',
                'package': "<module 'traceback2' from '/usr/lib/python3.7/site-packages/traceback2/__init__.py'>",
                'path': '/usr/lib/python3.7/site-packages/traceback2/'},
 'traitlets': {'name': 'traitlets',
               'package': "<module 'traitlets' from '/usr/lib/python3.7/site-packages/traitlets/__init__.py'>",
               'path': '/usr/lib/python3.7/site-packages/traitlets/',
               'ver': '4.3.2'},
 'trustme': {'name': 'trustme',
             'package': "<module 'trustme' from '/usr/lib/python3.7/site-packages/trustme/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/trustme/',
             'ver': '0.5.2'},
 'twisted': {'name': 'twisted', 'package': "<module 'twisted' (namespace)>"},
 'tzlocal': {'name': 'tzlocal',
             'package': "<module 'tzlocal' from '/usr/lib/python3.7/site-packages/tzlocal/__init__.py'>",
             'path': '/usr/lib/python3.7/site-packages/tzlocal/'},
 'umsgpack': {'name': 'umsgpack',
              'package': "<module 'umsgpack' from '/usr/lib/python3.7/site-packages/umsgpack.py'>",
              'path': '/usr/lib/python3.7/site-packages/umsgpack.py',
              'ver': '2.5.1'},
 'unittest2': {'name': 'unittest2',
               'package': "<module 'unittest2' from '/usr/lib/python3.7/site-packages/unittest2/__init__.py'>",
               'path': '/usr/lib/python3.7/site-packages/unittest2/',
               'ver': '1.1.0'},
 'uritemplate': {'name': 'uritemplate',
                 'package': "<module 'uritemplate' from '/usr/lib/python3.7/site-packages/uritemplate/__init__.py'>",
                 'path': '/usr/lib/python3.7/site-packages/uritemplate/',
                 'ver': '3.0.0'},
 'version': {'name': 'version',
             'package': "<module 'version' from '/usr/lib/python3.7/site-packages/version.py'>",
             'path': '/usr/lib/python3.7/site-packages/version.py',
             'ver': '0.0.0'},
 'versiontools': {'name': 'versiontools',
                  'package': "<module 'versiontools' from '/usr/lib/python3.7/site-packages/versiontools/__init__.py'>",
                  'path': '/usr/lib/python3.7/site-packages/versiontools/',
                  'ver': '1.9.1.final.0'},
 'webcolors': {'name': 'webcolors',
               'package': "<module 'webcolors' from '/usr/lib/python3.7/site-packages/webcolors.py'>",
               'path': '/usr/lib/python3.7/site-packages/webcolors.py',
               'ver': '1.8.1'},
 'webencodings': {'name': 'webencodings',
                  'package': "<module 'webencodings' from '/usr/lib/python3.7/site-packages/webencodings/__init__.py'>",
                  'path': '/usr/lib/python3.7/site-packages/webencodings/',
                  'ver': '0.5.1'},
 'xonsh': {'name': 'xonsh',
           'package': "<module 'xonsh' from '/usr/lib/python3.7/site-packages/xonsh/__init__.py'>",
           'path': '/usr/lib/python3.7/site-packages/xonsh/',
           'ver': '0.9.5'},
 'xprocess': {'name': 'xprocess',
              'package': "<module 'xprocess' from '/usr/lib/python3.7/site-packages/xprocess.py'>",
              'path': '/usr/lib/python3.7/site-packages/xprocess.py'}}

versioned = []
pathed = []
other = []

for name, dep in deps.items():
    assert name == dep['name']
    ver = dep.get('ver')
    if name == 'version':
        continue
    if dep.get('err') or '(namespace)' in dep.get('package', ''):
        continue
    path = dep.get('path')
    if path and ('/tmp/pytest' in path or 'tests' in path or '/test/' in path or '/_test/' in path or '/t/' in path or '/testing/' in path or path.startswith('./')):
        continue
    if ver:
        if ver == '0.0.0':
            continue
        versioned.append('{}=={}'.format(name, ver))
    elif dep.get('path'):
        pathed.append('{} # {}'.format(name, dep['path']))
    else:
        other.append('{} # {}'.format(name, dep.keys()))

for item in versioned + pathed + other:
    print(item)
